#ifndef PARALLEL_RAY_TRACER_CONSTANTS_HPP
#define PARALLEL_RAY_TRACER_CONSTANTS_HPP

const float PI = 3.14159265f;
const float EPS = 0.01f;
const int MAX_PATH = 2;
const int SAMPLES_PER_PIXEL = 64;

#endif //PARALLEL_RAY_TRACER_CONSTANTS_HPP
